# Sandpile Numbers
Studying generic sandpile numbers. We begin with the 3x3 case and try to determine each distinct value that can appear.

In [100]:
import numpy as np

In [ ]:
def collapse(num1, num2, modulus):
    ...

class Sandpile_Number():
    def __init__(self, *, dims=None, array=None, modulus=None):
        if array is not None:
            self.array = array
            self.dims = array.shape
        elif dims:
            self.dims = dims
            self.array = np.zeros(self.dims)
        else:
            self.dims = (3, 3)
            self.array = np.zeros(self.dims)

        if modulus is None:
            self.modulus = 3
        else:
            self.modulus = modulus

    def __add__(self, other):
        if self.modulus != other.modulus:
            raise ValueError(
                "Added sandpile numbers must have the same modulus. "
                f"Got {self.modulus}, {other.modulus} instead."
            )
        if self.dims != other.dims:
            raise ValueError(
                "Added sandpile numbers must have the same dimensions. "
                f"Got {self.dims}, {other.dims} instead."
            )

        res = Sandpile_Number(
            dims=self.dims,
            array=collapse(self, other, self.modulus),
            modulus=self.modulus
        )
        return res

In [102]:
arr1 = np.array([
    [1, 2, 1],
    [2, 1, 2],
    [1, 2, 1],
])

arr2 = np.array([
    [1, 1, 1],
    [1, 1, 1],
    [1, 1, 1],
])

num1 = Sandpile_Number(array=arr1)
num2 = Sandpile_Number(array=arr2)
res = num1 + num2
print(num1.array)
print(res.array)

[[1 2 1]
 [2 1 2]
 [1 2 1]]
[[2 0 2]
 [0 2 0]
 [2 0 2]]


# 2x2 Case

In [ ]:
num1 = Sandpile_Number(
    array=np.array([
        [1, 2],
        [2, 1],
    ])
)
res = num1 + num1
print(res.array)

[[0 0]
 [0 0]]
